# Generated by Django 5.1.7 on 2025-08-22 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_internal_id', models.CharField(db_index=True, help_text='ID interno de Orthanc', max_length=64)),
                ('study_instance_uid', models.CharField(help_text='Study Instance UID (0020,000D)', max_length=128, unique=True)),
                ('accession_number', models.CharField(blank=True, max_length=64, null=True)),
                ('contenido', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('draft', 'Borrador'), ('final', 'Final')], db_index=True, default='draft', max_length=16)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Informe',
                'verbose_name_plural': 'Informes',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['study_internal_id'], name='informes_re_study_i_55123c_idx'), models.Index(fields=['estado'], name='informes_re_estado_fca1d9_idx')],
            },
        ),
    ]
