# Generated by Django 5.1.7 on 2025-08-31 23:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0002_report_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('study_internal_id',), name='uniq_report_by_internal_study'),
        ),
    ]
