# Generated by Django 5.1.7 on 2025-09-14 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0007_report_version_loginforme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(help_text='Contenido de la adenda (HTML permitido básico).')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True, help_text='Permite ocultar una adenda sin eliminarla.')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adendas_informes', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adendas', to='informes.report')),
            ],
            options={
                'verbose_name': 'Adenda',
                'verbose_name_plural': 'Adendas',
                'ordering': ['creado'],
                'indexes': [models.Index(fields=['report', 'creado'], name='informes_ad_report__9784d8_idx')],
            },
        ),
    ]
