# Generated by Django 5.1.7 on 2025-09-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='PNG con fondo transparente recomendado', null=True, upload_to='firmas_medicos/'),
        ),
    ]
