# Generated by Django 5.1.7 on 2025-04-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlRecetas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_de_receta', models.DateField()),
                ('dias_para_el_vencimiento', models.IntegerField()),
            ],
        ),
    ]
