# Generated by Django 5.1.7 on 2025-04-13 19:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_ordenes', '0002_controlrecetas_identificador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_paciente', models.CharField(max_length=50, verbose_name='Identificador encriptado del paciente')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('dias_validez', models.IntegerField(choices=[(30, '30 días'), (60, '60 días')], default=30, verbose_name='Válido por')),
                ('medico', models.ForeignKey(limit_choices_to={'rol': 'medico'}, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_emitidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ControlRecetas',
        ),
    ]
