# Generated by Django 5.1.7 on 2025-09-17 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_ordenes', '0004_alter_ordenmedica_options_ordenmedica_renovada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmedica',
            name='last_action',
            field=models.CharField(blank=True, choices=[('creada', 'Creada'), ('renovada', 'Renovada'), ('editada', 'Editada')], default='', max_length=20, verbose_name='Última acción'),
        ),
        migrations.AddField(
            model_name='ordenmedica',
            name='last_action_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha última acción'),
        ),
        migrations.AddField(
            model_name='ordenmedica',
            name='last_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_operadas', to=settings.AUTH_USER_MODEL, verbose_name='Último operador'),
        ),
    ]
